blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/B5suDg7gu2
    about: For support questions and general chat.
  - name: Documentation
    url: https://musicseerr.com/
    about: Check the docs before opening an issue.
